---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Release.Name }}-traffic
  {{ template "iter8-traffic.labels" $ }}
rules:
{{- range $typeName, $type := .Values.resourceTypes }}
{{- if not $type.resource }}
{{- fail (print "resourceType \"" (print $typeName "\" does not have a resource parameter")) }}
{{- end }}
- apiGroups: ["{{- $type.group -}}"]
  resources: ["{{- $type.resource -}}"]
  verbs: ["get", "list", "watch", "patch", "update"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Release.Name }}-traffic
  {{ template "iter8-traffic.labels" $ }}
subjects:
- kind: ServiceAccount
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $.Release.Name }}-traffic
  apiGroup: rbac.authorization.k8s.io