apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  {{ template "iter8-autox.labels" . }}
stringData:
  chart-group-config.yaml: |
    specs:
    {{- range $name, $chartGroup := .Values.chartGroups }}
      {{ $name }}:
        trigger:
          group: {{ $chartGroup.trigger.group }}
          version: {{ $chartGroup.trigger.version }}
          resource: {{ $chartGroup.trigger.resource }}
          name: {{ $chartGroup.trigger.name }}
          namespace: {{ $chartGroup.trigger.namespace }}
        releaseSpecs:
        {{- range $cg := $chartGroup.releaseSpecs }}
          {{ $cg.chartID }}:
            repoURL: {{ $cg.repoURL }}
            name: {{ $cg.name }}
            values: {{ $cg.values }}
            version: {{ $cg.version }}
        {{- end }}
    {{- end }}
{{- range $name, $chartGroup := .Values.chartGroups }}
{{ $hash := print $chartGroup | sha256sum | trunc 5 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: autox-{{ $name }}-{{ $hash }}
  labels:
    iter8.tools/autox-group: {{ $name }}
{{- end }}