name: Lint Helm charts

on:
  pull_request:
    branches:
      - main

jobs:
  # Get the paths for the Helm charts to lint
  get_paths:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the paths for Helm charts to lint
        id: set-matrix
        run: |
          # Get paths (in string form)
          stringPaths=$(find -maxdepth 2 -path './charts/*')

          # Serialize paths into JSON array
          paths=$(jq -ncR '[inputs]' <<< "$stringPaths")

          # Output serialized paths
          echo "matrix=$paths" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  # Lint Helm charts based on paths provided by previous job
  lint:
    needs: get_paths

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.get_paths.outputs.matrix) }}

    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Helm charts in the ${{ matrix.version }} folder
        id: kube-lint-scan
        uses: stackrox/kube-linter-action@v1
        with:
          directory: ${{ matrix.version }}