name: Lint Helm charts

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [charts/abn, charts/autox, charts/iter8, charts/litmuschaos, charts/traffic]
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Helm charts in the ${{ matrix.version }} folder
        id: kube-lint-scan
        uses: stackrox/kube-linter-action@v1
        with:
          directory: ${{ matrix.version }}