name: Tests

on:
  pull_request:

jobs:
  kubernetes-http-experiment:
    name: Kubernetes HTTP load test    
    runs-on: ubuntu-latest
    steps:    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - uses: iter8-tools/iter8@v0.13

    - name: Start kind cluster
      uses: helm/kind-action@v1.5.0
      with:
        wait: 300s
        node_image: kindest/node:v1.22.17@sha256:c8a828709a53c25cbdc0790c8afe12f25538617c7be879083248981945c38693

    - name: Create app
      run: |
        kubectl create deployment httpbin --image=kennethreitz/httpbin
        kubectl expose deployment httpbin --type=ClusterIP --port=80
        kubectl wait --for=condition=available --timeout=60s deploy/httpbin

    - name: iter8 k launch
      run: |
        iter8 k launch \
        --localChart \
        --chartName charts/iter8 \
        --set tasks={http} \
        --set http.url="http://httpbin.default/get" \
        --set runner=job

    - name: Try other iter8 k commands
      run: |
        iter8 k assert -c completed -c nofailure --timeout 60s
        iter8 k report
        iter8 k log
        iter8 k delete
      
  kubernetes-grpc-experiment:
    name: Kubernetes gRPC load test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - uses: iter8-tools/iter8@v0.13

    - name: Start kind cluster
      uses: helm/kind-action@v1.5.0
      with:
        wait: 300s

    - name: Create app
      run: |
        kubectl create deploy hello --image=docker.io/grpc/java-example-hostname:latest --port=50051
        kubectl expose deploy hello --port=50051
        kubectl wait --for=condition=available --timeout=60s deploy/hello
        
    - name: iter8 k launch
      run: |
        iter8 k launch \
        --localChart \
        --chartName charts/iter8 \
        --set tasks={grpc} \
        --set grpc.host="hello.default:50051" \
        --set grpc.call="helloworld.Greeter.SayHello" \
        --set grpc.protoURL="https://raw.githubusercontent.com/grpc/grpc-go/master/examples/helloworld/helloworld/helloworld.proto" \
        --set runner=job

    - name: Try other iter8 k commands
      run: |
        iter8 k assert -c completed -c nofailure --timeout 60s
        iter8 k report
        iter8 k log
        iter8 k delete

  kubernetes-autox:
    name: Kubernetes autox test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - uses: iter8-tools/iter8@v0.13

    - name: Start kind cluster
      uses: helm/kind-action@v1.5.0
      with:
        wait: 300s

    - name: Create namespace
      run: |
        kubectl create namespace argocd
        
    - name: Start AutoX controller
      run: |
        helm install autox charts/autox \
        --set 'groups.httpbin.trigger.name=httpbin' \
        --set 'groups.httpbin.trigger.namespace=default' \
        --set 'groups.httpbin.trigger.group=apps' \
        --set 'groups.httpbin.trigger.version=v1' \
        --set 'groups.httpbin.trigger.resource=deployments' \
        --set 'groups.httpbin.specs.iter8.name=iter8' \
        --set 'groups.httpbin.specs.iter8.values.tasks={ready,http,assess}' \
        --set 'groups.httpbin.specs.iter8.values.ready.deploy=httpbin' \
        --set 'groups.httpbin.specs.iter8.values.ready.service=httpbin' \
        --set 'groups.httpbin.specs.iter8.values.ready.timeout=60s' \
        --set 'groups.httpbin.specs.iter8.values.http.url=http://httpbin.default/get' \
        --set 'groups.httpbin.specs.iter8.values.assess.SLOs.upper.http/error-count=0' \
        --set 'groups.httpbin.specs.iter8.values.assess.SLOs.upper.http/latency-mean=50' \
        --set 'groups.httpbin.specs.iter8.version=0.13.0' \
        --set 'groups.httpbin.specs.iter8.values.runner=job'

    - name: Check AutoX controller
      run: kubectl wait --for=condition=available --timeout=60s deploy/autox -n argocd
