name: Tests

on:
  pull_request:

jobs:
  kubernetes-http-experiment:
    name: Kubernetes HTTP load test    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: 
        - kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
        - kindest/node:v1.25.8@sha256:00d3f5314cc35327706776e95b2f8e504198ce59ac545d0200a89e69fce10b7f
        - kindest/node:v1.24.12@sha256:1e12918b8bc3d4253bc08f640a231bb0d3b2c5a9b28aa3f2ca1aee93e1e8db16
        - kindest/node:v1.23.17@sha256:e5fd1d9cd7a9a50939f9c005684df5a6d145e8d695e78463637b79464292e66c
        - kindest/node:v1.22.17@sha256:c8a828709a53c25cbdc0790c8afe12f25538617c7be879083248981945c38693
        - kindest/node:v1.21.14@sha256:27ef72ea623ee879a25fe6f9982690a3e370c68286f4356bf643467c552a3888
        - kindest/node:v1.27.1@sha256:9915f5629ef4d29f35b478e819249e89cfaffcbfeebda4324e5c01d53d937b09
        - kindest/node:v1.27.0@sha256:c6b22e613523b1af67d4bc8a0c38a4c3ea3a2b8fbc5b367ae36345c9cb844518

    steps:    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get modified files in the charts/iter8 folder
      id: modified-files
      uses: tj-actions/changed-files@v35
      with:
        files: charts/iter8

    - uses: iter8-tools/iter8@v0.13
      if: steps.modified-files.outputs.any_modified == 'true'

    - name: Start kind cluster ${{ matrix.version }}
      uses: helm/kind-action@v1.5.0
      if: steps.modified-files.outputs.any_modified == 'true'
      with:
        wait: 300s
        node_image: ${{ matrix.version }}

    - name: Create app
      if: steps.modified-files.outputs.any_modified == 'true'
      run: |
        kubectl create deployment httpbin --image=kennethreitz/httpbin
        kubectl expose deployment httpbin --type=ClusterIP --port=80
        kubectl wait --for=condition=available --timeout=60s deploy/httpbin

    - name: iter8 k launch
      if: steps.modified-files.outputs.any_modified == 'true'
      run: |
        iter8 k launch \
        --localChart \
        --chartName charts/iter8 \
        --set tasks={http} \
        --set http.url="http://httpbin.default/get" \
        --set runner=job

    - name: Try other iter8 k commands
      if: steps.modified-files.outputs.any_modified == 'true'
      run: |
        iter8 k assert -c completed -c nofailure --timeout 60s
        iter8 k report
        iter8 k log
        iter8 k delete
      
  kubernetes-grpc-experiment:
    name: Kubernetes gRPC load test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
        - kindest/node:v1.25.8@sha256:00d3f5314cc35327706776e95b2f8e504198ce59ac545d0200a89e69fce10b7f
        - kindest/node:v1.24.12@sha256:1e12918b8bc3d4253bc08f640a231bb0d3b2c5a9b28aa3f2ca1aee93e1e8db16
        - kindest/node:v1.23.17@sha256:e5fd1d9cd7a9a50939f9c005684df5a6d145e8d695e78463637b79464292e66c
        - kindest/node:v1.22.17@sha256:c8a828709a53c25cbdc0790c8afe12f25538617c7be879083248981945c38693
        - kindest/node:v1.21.14@sha256:27ef72ea623ee879a25fe6f9982690a3e370c68286f4356bf643467c552a3888
        - kindest/node:v1.27.1@sha256:9915f5629ef4d29f35b478e819249e89cfaffcbfeebda4324e5c01d53d937b09
        - kindest/node:v1.27.0@sha256:c6b22e613523b1af67d4bc8a0c38a4c3ea3a2b8fbc5b367ae36345c9cb844518

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get modified files in the charts/iter8 folder
      id: modified-files
      uses: tj-actions/changed-files@v35
      with:
        files: charts/iter8
    
    - uses: iter8-tools/iter8@v0.13
      if: steps.modified-files.outputs.any_modified == 'true'

    - name: Start kind cluster ${{ matrix.version }}
      uses: helm/kind-action@v1.5.0
      if: steps.modified-files.outputs.any_modified == 'true'
      with:
        wait: 300s
        node_image: ${{ matrix.version }}

    - name: Create app
      if: steps.modified-files.outputs.any_modified == 'true'
      run: |
        kubectl create deploy hello --image=docker.io/grpc/java-example-hostname:latest --port=50051
        kubectl expose deploy hello --port=50051
        kubectl wait --for=condition=available --timeout=60s deploy/hello
        
    - name: iter8 k launch
      if: steps.modified-files.outputs.any_modified == 'true'
      run: |
        iter8 k launch \
        --localChart \
        --chartName charts/iter8 \
        --set tasks={grpc} \
        --set grpc.host="hello.default:50051" \
        --set grpc.call="helloworld.Greeter.SayHello" \
        --set grpc.protoURL="https://raw.githubusercontent.com/grpc/grpc-go/master/examples/helloworld/helloworld/helloworld.proto" \
        --set runner=job

    - name: Try other iter8 k commands
      if: steps.modified-files.outputs.any_modified == 'true'
      run: |
        iter8 k assert -c completed -c nofailure --timeout 60s
        iter8 k report
        iter8 k log
        iter8 k delete

  kubernetes-autox:
    name: Kubernetes AutoX test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
        - kindest/node:v1.25.8@sha256:00d3f5314cc35327706776e95b2f8e504198ce59ac545d0200a89e69fce10b7f
        - kindest/node:v1.24.12@sha256:1e12918b8bc3d4253bc08f640a231bb0d3b2c5a9b28aa3f2ca1aee93e1e8db16
        - kindest/node:v1.23.17@sha256:e5fd1d9cd7a9a50939f9c005684df5a6d145e8d695e78463637b79464292e66c
        - kindest/node:v1.22.17@sha256:c8a828709a53c25cbdc0790c8afe12f25538617c7be879083248981945c38693
        - kindest/node:v1.21.14@sha256:27ef72ea623ee879a25fe6f9982690a3e370c68286f4356bf643467c552a3888
        - kindest/node:v1.27.1@sha256:9915f5629ef4d29f35b478e819249e89cfaffcbfeebda4324e5c01d53d937b09
        - kindest/node:v1.27.0@sha256:c6b22e613523b1af67d4bc8a0c38a4c3ea3a2b8fbc5b367ae36345c9cb844518

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get modified files in the charts/autox folder
      id: modified-files
      uses: tj-actions/changed-files@v35
      with:
        files: charts/autox

    - uses: iter8-tools/iter8@v0.13
      if: steps.modified-files.outputs.any_modified == 'true'

    - name: Start kind cluster ${{ matrix.version }}
      uses: helm/kind-action@v1.5.0
      if: steps.modified-files.outputs.any_modified == 'true'
      with:
        wait: 300s
        node_image: ${{ matrix.version }}

    - name: Create namespace
      if: steps.modified-files.outputs.any_modified == 'true'
      run: |
        kubectl create namespace argocd
        
    - name: Start AutoX controller
      if: steps.modified-files.outputs.any_modified == 'true'
      run: |
        helm install autox charts/autox \
        --set 'groups.httpbin.trigger.name=httpbin' \
        --set 'groups.httpbin.trigger.namespace=default' \
        --set 'groups.httpbin.trigger.group=apps' \
        --set 'groups.httpbin.trigger.version=v1' \
        --set 'groups.httpbin.trigger.resource=deployments' \
        --set 'groups.httpbin.specs.iter8.name=iter8' \
        --set 'groups.httpbin.specs.iter8.values.tasks={ready,http,assess}' \
        --set 'groups.httpbin.specs.iter8.values.ready.deploy=httpbin' \
        --set 'groups.httpbin.specs.iter8.values.ready.service=httpbin' \
        --set 'groups.httpbin.specs.iter8.values.ready.timeout=60s' \
        --set 'groups.httpbin.specs.iter8.values.http.url=http://httpbin.default/get' \
        --set 'groups.httpbin.specs.iter8.values.assess.SLOs.upper.http/error-count=0' \
        --set 'groups.httpbin.specs.iter8.values.assess.SLOs.upper.http/latency-mean=50' \
        --set 'groups.httpbin.specs.iter8.version=0.13.0' \
        --set 'groups.httpbin.specs.iter8.values.runner=job'

    - name: Check AutoX controller
      if: steps.modified-files.outputs.any_modified == 'true'
      run: kubectl wait --for=condition=available --timeout=60s deploy/autox -n argocd
