name: tests

on:
  pull_request:

jobs:
  kubernetes-http-experiment:
    name: Kubernetes http load test    
    runs-on: ubuntu-latest
    steps:    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - uses: iter8-tools/iter8@v0.13

    - name: Start kind cluster
      uses: helm/kind-action@v1.5.0
      with:
        wait: 300s

    - name: create app
      run: |
        kubectl create deployment httpbin --image=kennethreitz/httpbin
        kubectl expose deployment httpbin --type=ClusterIP --port=80
        kubectl wait --for=condition=available --timeout=60s deploy/httpbin

    - name: iter8 k launch
      run: |
        iter8 k launch \
        --localChart \
        --chartName charts/iter8 \
        --set tasks={http} \
        --set http.url="http://httpbin.default/get" \
        --set runner=job

    - name: try other iter8 k commands
      run: |
        iter8 k assert -c completed -c nofailure --timeout 60s
        iter8 k report
        iter8 k log
        iter8 k delete
