name: Version bump check

on:
  pull_request:
    branches:
      - main
      - ssa
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [charts/abn, charts/autox, charts/iter8]
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get modified files in the ${{ matrix.version }} folder
        id: modified-files
        uses: tj-actions/changed-files@v35
        with:
          files: ${{ matrix.version }}

      - name: Run step if any file(s) in the ${{ matrix.version }} folder was modified
        if: steps.modified-files.outputs.any_modified == 'true'
        run: |
          chartFile="${{ matrix.version }}/Chart.yaml"

          # Get git diff of main branch and PR branch
          gitDiff=$(git diff --name-only origin/main origin/${GITHUB_HEAD_REF})

          echo "$diffFile"

          # Deletion and addition in Chart.yaml
          part1=$'--- a/'
          part2=$'\n+++ b/'
          diffFile="$part1$chartFile$part2$chartFile"

          # Deletion and addition of version in Chart.yaml
          deleteVersion="-version:"
          addVersion="+version:"

          if [[ "$gitDiff" == *"$diffFile"* ]] && [[ "$gitDiff" == *$deleteVersion* ]] && [[ "$gitDiff" == *$addVersion* ]]; 
          then
            echo "version in $chartFile has been modified"
          else
            echo "version in $chartFile needs to be modified"
            exit 1
          fi